package ipldgit

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	ipld "github.com/ipld/go-ipld-prime"
)

var _ ipld.Node = nil // suppress errors when this dependency is not referenced
// Type is a struct embeding a NodePrototype/Type for every Node implementation in this package.
// One of its major uses is to start the construction of a value.
// You can use it like this:
//
// 		ipldgit.Type.YourTypeName.NewBuilder().BeginMap() //...
//
// and:
//
// 		ipldgit.Type.OtherTypeName.NewBuilder().AssignString("x") // ...
//
var Type typeSlab

type typeSlab struct {
	Blob              _Blob__Prototype
	Blob__Repr        _Blob__ReprPrototype
	Commit            _Commit__Prototype
	Commit__Repr      _Commit__ReprPrototype
	GpgSig            _GpgSig__Prototype
	GpgSig__Repr      _GpgSig__ReprPrototype
	Link              _Link__Prototype
	Link__Repr        _Link__ReprPrototype
	LinkTree          _LinkTree__Prototype
	LinkTree__Repr    _LinkTree__ReprPrototype
	ListParents       _ListParents__Prototype
	ListParents__Repr _ListParents__ReprPrototype
	ListString        _ListString__Prototype
	ListString__Repr  _ListString__ReprPrototype
	ListTag           _ListTag__Prototype
	ListTag__Repr     _ListTag__ReprPrototype
	PersonInfo        _PersonInfo__Prototype
	PersonInfo__Repr  _PersonInfo__ReprPrototype
	String            _String__Prototype
	String__Repr      _String__ReprPrototype
	Tag               _Tag__Prototype
	Tag__Repr         _Tag__ReprPrototype
	Tree              _Tree__Prototype
	Tree__Repr        _Tree__ReprPrototype
	TreeEntry         _TreeEntry__Prototype
	TreeEntry__Repr   _TreeEntry__ReprPrototype
}

// --- type definitions follow ---

// Blob matches the IPLD Schema type "Blob".  It has bytes kind.
type Blob = *_Blob
type _Blob struct{ x []byte }

// Commit matches the IPLD Schema type "Commit".  It has Struct type-kind, and may be interrogated like map kind.
type Commit = *_Commit
type _Commit struct {
	GitTree   _LinkTree
	Parents   _ListParents
	Message   _String
	Author    _PersonInfo__Maybe
	Committer _PersonInfo__Maybe
	Encoding  _String__Maybe
	Sig       _GpgSig__Maybe
	MergeTag  _ListTag
	Other     _ListString
}

// GpgSig matches the IPLD Schema type "GpgSig".  It has string kind.
type GpgSig = *_GpgSig
type _GpgSig struct{ x string }

// Link matches the IPLD Schema type "Link".  It has link kind.
type Link = *_Link
type _Link struct{ x ipld.Link }

// LinkTree matches the IPLD Schema type "LinkTree".  It has link kind.
type LinkTree = *_LinkTree
type _LinkTree struct{ x ipld.Link }

// ListParents matches the IPLD Schema type "ListParents".  It has list kind.
type ListParents = *_ListParents
type _ListParents struct {
	x []_Link
}

// ListString matches the IPLD Schema type "ListString".  It has list kind.
type ListString = *_ListString
type _ListString struct {
	x []_String
}

// ListTag matches the IPLD Schema type "ListTag".  It has list kind.
type ListTag = *_ListTag
type _ListTag struct {
	x []_Tag
}

// PersonInfo matches the IPLD Schema type "PersonInfo".  It has Struct type-kind, and may be interrogated like map kind.
type PersonInfo = *_PersonInfo
type _PersonInfo struct {
	Name     _String
	Email    _String
	Date     _String
	Timezone _String
}

// String matches the IPLD Schema type "String".  It has string kind.
type String = *_String
type _String struct{ x string }

// Tag matches the IPLD Schema type "Tag".  It has Struct type-kind, and may be interrogated like map kind.
type Tag = *_Tag
type _Tag struct {
	Object  _Link
	TagType _String
	Tag     _String
	Tagger  _PersonInfo
	Text    _String
}

// Tree matches the IPLD Schema type "Tree".  It has list kind.
type Tree = *_Tree
type _Tree struct {
	x []_TreeEntry
}

// TreeEntry matches the IPLD Schema type "TreeEntry".  It has Struct type-kind, and may be interrogated like map kind.
type TreeEntry = *_TreeEntry
type _TreeEntry struct {
	Mode _String
	Name _String
	Hash _Link
}
